### ISSUE TITLE
Multi instance mode does not work with TLS template

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/admin#2]
For TLS-based deployments, the mqtt and router components needs secrets with the certificate keys to be available. Right now, the secrets are assumed to be added manually by the oc tool, but they are not accessible from within each instance's namespace.

Ideally each instance would have separate secrets.

**Comment by grs** [comment]
So the instance API could allow a certificate to be uploaded? What might also be nice would be to see if there were anyway to use lets encrypt/acme to automatically generate a valid certificate for the instance if one was not supplied?

**Comment by lulf** [comment]
That would be one way, though I'm not sure if there are other mechanisms that are more appropriate. We would have to enable ssl on the address-controller and add secrets for that as well, otherwise we would send the keys unencrypted.

Agreed it would be nice to use the letsencrypt/acme controller by default.
